package view;

import dao.PessoaDAO;
import javax.swing.DefaultListModel;

/**
 *
 * @author Sabrina
 * @since 02/2021
 * @version 1.0
 *
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

    }

    /**
     * @deprecated Não utilizado
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pessoaList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        salaList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        espacoCafeList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        OptionsMainMenu = new javax.swing.JMenu();
        AddMenu = new javax.swing.JMenu();
        addPessoaMenuItem = new javax.swing.JMenuItem();
        addSalaMenuItem = new javax.swing.JMenuItem();
        addEspacoCafeMenuItem = new javax.swing.JMenuItem();
        SearchMenu = new javax.swing.JMenu();
        searchPessoaMenuItem = new javax.swing.JMenuItem();
        searchSalaMenuItem = new javax.swing.JMenuItem();
        searchEspacoCafeMenuItem = new javax.swing.JMenuItem();
        closeMenu = new javax.swing.JMenu();
        updateMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jScrollPane2.setViewportView(pessoaList);

        jScrollPane3.setViewportView(salaList);

        jScrollPane1.setViewportView(espacoCafeList);

        jLabel1.setText("Espaço de Café");

        jLabel2.setText("Sala");

        jLabel3.setText("Nome");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(75, 75, 75))))
        );

        getContentPane().add(MainPanel, "card2");

        OptionsMainMenu.setText("Opções");

        AddMenu.setText("Adicionar");

        addPessoaMenuItem.setText("Pessoa");
        addPessoaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPessoaMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(addPessoaMenuItem);

        addSalaMenuItem.setText("Sala");
        addSalaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalaMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(addSalaMenuItem);

        addEspacoCafeMenuItem.setText("Espaço de café");
        addEspacoCafeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEspacoCafeMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(addEspacoCafeMenuItem);

        OptionsMainMenu.add(AddMenu);

        SearchMenu.setText("Pesquisar");

        searchPessoaMenuItem.setText("Pessoa");
        searchPessoaMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPessoaMenuItemMouseClicked(evt);
            }
        });
        searchPessoaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPessoaMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(searchPessoaMenuItem);

        searchSalaMenuItem.setText("Sala");
        searchSalaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSalaMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(searchSalaMenuItem);

        searchEspacoCafeMenuItem.setText("Espaço de café");
        searchEspacoCafeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEspacoCafeMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(searchEspacoCafeMenuItem);

        OptionsMainMenu.add(SearchMenu);

        MainMenuBar.add(OptionsMainMenu);

        closeMenu.setText("Fechar todas as Janelas");
        closeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMenuMouseClicked(evt);
            }
        });
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        MainMenuBar.add(closeMenu);

        updateMenu.setText("Atualizar");
        updateMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMenuMouseClicked(evt);
            }
        });
        updateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuActionPerformed(evt);
            }
        });
        MainMenuBar.add(updateMenu);

        setJMenuBar(MainMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPessoaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPessoaMenuItemActionPerformed
        // Chama a view de adicionar pessoa
        PessoaView p = new PessoaView();
        p.setVisible(true);
    }//GEN-LAST:event_addPessoaMenuItemActionPerformed

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed

    }//GEN-LAST:event_closeMenuActionPerformed

    private void searchPessoaMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPessoaMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPessoaMenuItemMouseClicked

    private void searchPessoaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPessoaMenuItemActionPerformed
        // Chama a view de busca por pessoa
        PessoaSearchView psv = new PessoaSearchView();
        psv.setVisible(true);
    }//GEN-LAST:event_searchPessoaMenuItemActionPerformed

    private void updateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_updateMenuActionPerformed

    private void addSalaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalaMenuItemActionPerformed
        // Chama a view de adicionar por Sala
        SalaView s = new SalaView();
        s.setVisible(true);
    }//GEN-LAST:event_addSalaMenuItemActionPerformed

    private void addEspacoCafeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEspacoCafeMenuItemActionPerformed
        // Chama a view de adicionar por Espaço de café
        EspacoCafeView ec = new EspacoCafeView();
        ec.setVisible(true);
    }//GEN-LAST:event_addEspacoCafeMenuItemActionPerformed

    private void closeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuMouseClicked
        // Encerra a aplicação
        this.dispose();
    }//GEN-LAST:event_closeMenuMouseClicked

    private void searchSalaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSalaMenuItemActionPerformed
        // Chama a view de busca por Sala
        SalaSearchView sv = new SalaSearchView();
        sv.setVisible(true);
    }//GEN-LAST:event_searchSalaMenuItemActionPerformed

    private void searchEspacoCafeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEspacoCafeMenuItemActionPerformed
        // Chama a view de busca por Espaço de café
        EspacoCafeSearchView ecsv = new EspacoCafeSearchView();
        ecsv.setVisible(true);
    }//GEN-LAST:event_searchEspacoCafeMenuItemActionPerformed

    private void updateMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMenuMouseClicked
        // Atualiza as JLists

        PessoaDAO pd = new PessoaDAO();
        DefaultListModel model = new DefaultListModel();
        DefaultListModel model1 = new DefaultListModel();
        DefaultListModel model2 = new DefaultListModel();
        pessoaList.setModel(model);
        salaList.setModel(model1);
        espacoCafeList.setModel(model2);
        for (int i = 0; i < pd.queryByController().size(); i++) {

            model.addElement(pd.queryByController().get(i).getNome().concat(" " + pd.queryByController().get(i).getSobrenome()));
            model1.addElement(pd.queryByController().get(i).getIdSala());
            model2.addElement(pd.queryByController().get(i).getIdEspacoCafe());
        }
    }//GEN-LAST:event_updateMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddMenu;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenu OptionsMainMenu;
    private javax.swing.JMenu SearchMenu;
    private javax.swing.JMenuItem addEspacoCafeMenuItem;
    private javax.swing.JMenuItem addPessoaMenuItem;
    private javax.swing.JMenuItem addSalaMenuItem;
    private javax.swing.JMenu closeMenu;
    private javax.swing.JList<String> espacoCafeList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> pessoaList;
    private javax.swing.JList<String> salaList;
    private javax.swing.JMenuItem searchEspacoCafeMenuItem;
    private javax.swing.JMenuItem searchPessoaMenuItem;
    private javax.swing.JMenuItem searchSalaMenuItem;
    private javax.swing.JMenu updateMenu;
    // End of variables declaration//GEN-END:variables
}
